In [2]:
import gym
import random
import pandas as pd

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [4]:
import numpy as np
# Patch Gym compatibility with modern NumPy
np.bool8 = bool

import gym
import pandas as pd

env = gym.make('FrozenLake-v1')
alpha = 0.85
gamma = 0.90

#and the epsilon value:
epsilon = 0.8

num_episodes = 50000
num_timesteps = 1000

def random_policy():
  return env.action_space.sample()
env.action_space

#Initialising the state values to zero.
#Create a empty dictionary : for storing the value of states (16 states, 4x4 grid)
v = {}
for s in range (env.observation_space.n):
  #Cannot make the observation space discrete, since it is 5x5 continous space
  v[s]=0.0

#Compute the policy
#For each episode:
for i in range(num_episodes):
#Initialize the state by resetting the environment:
    s = env.reset()
#For each step in the episode:
    for t in range(num_timesteps):
# Select an action according to the random policy
        a = random_policy()
#Perform the selected action and store the next state information:
        s_, r, done, _ = env.step(a)
#Compute the value of state as
        v[s] += alpha * (r + gamma * v[s_]-v[s]) # TD update rule
        s = s_
#If the current state is the terminal state, then break:
        if done:
            break

df = pd.DataFrame(list(v.items()), columns=['state', 'value'])
df

/usr/local/lib/python3.13/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.13/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(

    state     value
0       0  0.000958
1       1  0.000169
2       2  0.000531
3       3  0.000411
4       4  0.000099
5       5  0.000000
6       6  0.000059
7       7  0.000000
8       8  0.010482
9       9  0.001731
10     10  0.166887
11     11  0.000000
12     12  0.000000
13     13  0.742996
14     14  0.877328
15     15  0.000000

/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

SARSA

In [5]:

def epsilon_greedy(state, epsilon):
    if random.uniform(0,1) < epsilon:
        return env.action_space.sample()
    else:
        return max(list(range(env.action_space.n)), key = lambda x:Q[(state,x)])

In [6]:

Q = {}
for s in range(env.observation_space.n):
    for a in range(env.action_space.n):
        Q[(s,a)] = 0.0

In [7]:

for i in range(num_episodes):

    s = env.reset()

    a = epsilon_greedy(s,epsilon)

    for t in range(num_timesteps):

        s_, r, done, _ = env.step(a)

        a_ = epsilon_greedy(s_,epsilon)
        Q[(s,a)] += alpha * (r + gamma * Q[(s_,a_)]-Q[(s,a)])

        s = s_
        a = a_

        if done:
            break

In [8]:
df = pd.DataFrame(list(Q.items()), columns=['state', 'value'])

In [9]:
df

      state     value
0    (0, 0)  0.000164
1    (0, 1)  0.002252
2    (0, 2)  0.000423
3    (0, 3)  0.001176
4    (1, 0)  0.000056
..      ...       ...
59  (14, 3)  0.097145
60  (15, 0)  0.000000
61  (15, 1)  0.000000
62  (15, 2)  0.000000
63  (15, 3)  0.000000

[64 rows x 2 columns]

/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Q-LEARNING

In [10]:
import numpy as np

In [11]:

for i in range(num_episodes):

    s = env.reset()

    for t in range(num_timesteps):

        a = epsilon_greedy(s,epsilon)

        s_, r, done, _ = env.step(a)

        a_ = np.argmax([Q[(s_,a)] for a in range(env.action_space.n)])

        Q[(s,a)] += alpha * (r + gamma * Q[(s_,a_)]-Q[(s,a)])

        s = s_
        #a = a_

        if done:
            break

In [12]:
df = pd.DataFrame(list(Q.items()), columns=['state', 'value'])

In [13]:
df

      state     value
0    (0, 0)  0.327297
1    (0, 1)  0.377775
2    (0, 2)  0.403612
3    (0, 3)  0.322281
4    (1, 0)  0.349128
..      ...       ...
59  (14, 3)  0.970825
60  (15, 0)  0.000000
61  (15, 1)  0.000000
62  (15, 2)  0.000000
63  (15, 3)  0.000000

[64 rows x 2 columns]

/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)